//! Reconciliation logic for OmegonAgent CRDs.
//!
//! Watches OmegonAgent resources and ensures the corresponding k8s primitives
//! (Deployment/CronJob, ConfigMap, Service) match the desired state.

use std::sync::Arc;

use k8s_openapi::api::{
    apps::v1::Deployment,
    batch::v1::CronJob,
    core::v1::{ConfigMap, Service},
};
use kube::{
    Api, Client, Resource, ResourceExt,
    api::{Patch, PatchParams},
    runtime::controller::Action,
};
use serde_json::json;
use tracing::{info, warn};

use crate::crd::{AgentMode, OmegonAgent};

/// Shared state across reconcile calls.
pub struct Context {
    pub client: Client,
}

/// Reconcile a single OmegonAgent resource.
pub async fn reconcile(agent: Arc<OmegonAgent>, ctx: Arc<Context>) -> Result<Action, kube::Error> {
    let client = &ctx.client;
    let ns = agent.namespace().unwrap_or_else(|| "default".into());
    let name = agent.name_any();

    info!(agent = %name, namespace = %ns, mode = ?agent.spec.mode, "reconciling");

    // Ensure ConfigMap for vox.toml
    reconcile_configmap(client, &agent, &ns, &name).await?;

    // Ensure workload (Deployment or CronJob)
    match agent.spec.mode {
        AgentMode::Daemon => {
            reconcile_deployment(client, &agent, &ns, &name).await?;
            reconcile_service(client, &agent, &ns, &name).await?;
        }
        AgentMode::Cronjob => {
            reconcile_cronjob(client, &agent, &ns, &name).await?;
        }
    }

    info!(agent = %name, "reconciliation complete");
    Ok(Action::requeue(std::time::Duration::from_secs(300)))
}

/// Handle reconciliation errors.
pub fn error_policy(agent: Arc<OmegonAgent>, error: &kube::Error, _ctx: Arc<Context>) -> Action {
    warn!(
        agent = %agent.name_any(),
        error = %error,
        "reconcile error — retrying in 30s"
    );
    Action::requeue(std::time::Duration::from_secs(30))
}

async fn reconcile_configmap(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<ConfigMap> = Api::namespaced(client.clone(), ns);
    let cm_name = format!("{name}-vox");

    let mut vox_toml = String::from("# Generated by auspex-operator\n");

    if let Some(ref discord) = agent.spec.vox.discord {
        vox_toml.push_str("\n[discord]\n");
        vox_toml.push_str(&format!(
            "require_mention = {}\n",
            discord.require_mention
        ));
        if let Some(ref gid) = discord.guild_id {
            vox_toml.push_str(&format!("guild_id = \"{gid}\"\n"));
        }
    }

    if let Some(ref slack) = agent.spec.vox.slack {
        vox_toml.push_str("\n[slack]\n");
        if let Some(ref ws) = slack.workspace {
            vox_toml.push_str(&format!("workspace = \"{ws}\"\n"));
        }
    }

    let cm = json!({
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": cm_name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "data": {
            "vox.toml": vox_toml,
        }
    });

    api.patch(
        &cm_name,
        &PatchParams::apply("auspex-operator"),
        &Patch::Apply(cm),
    )
    .await?;
    Ok(())
}

async fn reconcile_deployment(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<Deployment> = Api::namespaced(client.clone(), ns);

    let deploy = json!({
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "spec": {
            "replicas": 1,
            "selector": { "matchLabels": { "styrene.sh/agent": name } },
            "template": {
                "metadata": { "labels": { "styrene.sh/agent": name } },
                "spec": pod_spec(agent, name),
            }
        }
    });

    api.patch(name, &PatchParams::apply("auspex-operator"), &Patch::Apply(deploy))
        .await?;
    Ok(())
}

async fn reconcile_cronjob(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<CronJob> = Api::namespaced(client.clone(), ns);
    let schedule = agent.spec.schedule.as_deref().unwrap_or("0 * * * *");

    let mut spec = pod_spec(agent, name);
    spec.as_object_mut().unwrap().insert("restartPolicy".into(), json!("Never"));

    let cj = json!({
        "apiVersion": "batch/v1",
        "kind": "CronJob",
        "metadata": {
            "name": name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "spec": {
            "schedule": schedule,
            "concurrencyPolicy": "Forbid",
            "successfulJobsHistoryLimit": 3,
            "failedJobsHistoryLimit": 3,
            "jobTemplate": {
                "spec": {
                    "backoffLimit": 1,
                    "template": {
                        "metadata": { "labels": { "styrene.sh/agent": name } },
                        "spec": spec,
                    }
                }
            }
        }
    });

    api.patch(name, &PatchParams::apply("auspex-operator"), &Patch::Apply(cj))
        .await?;
    Ok(())
}

async fn reconcile_service(
    client: &Client,
    _agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<Service> = Api::namespaced(client.clone(), ns);

    let svc = json!({
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": name,
            "namespace": ns,
        },
        "spec": {
            "selector": { "styrene.sh/agent": name },
            "ports": [{
                "port": 7842,
                "targetPort": 7842,
                "protocol": "TCP",
                "name": "control",
            }],
        }
    });

    api.patch(name, &PatchParams::apply("auspex-operator"), &Patch::Apply(svc))
        .await?;
    Ok(())
}

fn pod_spec(agent: &OmegonAgent, name: &str) -> serde_json::Value {
    let mut env = vec![];
    if let Some(ref discord) = agent.spec.vox.discord {
        if let Some(ref gid) = discord.guild_id {
            env.push(json!({"name": "VOX_DISCORD_GUILD_ID", "value": gid}));
        }
    }

    let mut volume_mounts = vec![json!({
        "name": "vox-config",
        "mountPath": "/root/.config/vox",
    })];
    let mut volumes = vec![json!({
        "name": "vox-config",
        "configMap": { "name": format!("{name}-vox") },
    })];

    if let Some(ref auth_secret) = agent.spec.secrets.auth_json_secret {
        volume_mounts.push(json!({
            "name": "auth-json",
            "mountPath": "/config/omegon",
            "readOnly": true,
        }));
        volumes.push(json!({
            "name": "auth-json",
            "secret": {
                "secretName": auth_secret,
                "items": [{"key": "auth.json", "path": "auth.json"}],
            },
        }));
    }

    let mut env_from = vec![];
    if let Some(ref secret_name) = agent.spec.secrets.secret_name {
        env_from.push(json!({"secretRef": {"name": secret_name}}));
    }

    json!({
        "containers": [{
            "name": "agent",
            "image": &agent.spec.image,
            "args": [
                "--agent", &agent.spec.agent,
                "--model", &agent.spec.model,
            ],
            "ports": [{"containerPort": 7842}],
            "env": env,
            "envFrom": env_from,
            "volumeMounts": volume_mounts,
        }],
        "volumes": volumes,
    })
}

fn owner_ref(agent: &OmegonAgent) -> serde_json::Value {
    json!({
        "apiVersion": "styrene.sh/v1alpha1",
        "kind": "OmegonAgent",
        "name": agent.name_any(),
        "uid": agent.metadata.uid.as_deref().unwrap_or(""),
        "controller": true,
        "blockOwnerDeletion": true,
    })
}
