//! Reconciliation logic for OmegonAgent CRDs.
//!
//! Watches OmegonAgent resources and ensures the corresponding k8s primitives
//! (Deployment/CronJob, ConfigMap, Service) match the desired state.

use std::sync::Arc;

use k8s_openapi::api::{
    apps::v1::Deployment,
    batch::v1::{CronJob, Job},
    core::v1::{ConfigMap, Service},
};
use kube::{
    Api, Client, ResourceExt,
    api::{Patch, PatchParams},
    runtime::controller::Action,
};
use serde_json::json;
use tracing::{info, warn};

use crate::crd::{AgentMode, OmegonAgent};

const CONTROL_TLS_MOUNT_PATH: &str = "/run/omegon/control-tls";

/// Default sidecar images. Override via AUSPEX_STYRENED_IMAGE / AUSPEX_AETHER_IMAGE env vars.
fn styrened_image() -> String {
    std::env::var("AUSPEX_STYRENED_IMAGE")
        .unwrap_or_else(|_| "ghcr.io/styrene-lab/styrened:0.5".into())
}

fn aether_image() -> String {
    std::env::var("AUSPEX_AETHER_IMAGE").unwrap_or_else(|_| "ghcr.io/styrene-lab/aether:0.3".into())
}

/// Shared state across reconcile calls.
pub struct Context {
    pub client: Client,
    /// When set, restricts all operations to this namespace.
    pub watch_namespace: Option<String>,
}

/// Reconcile a single OmegonAgent resource.
pub async fn reconcile(agent: Arc<OmegonAgent>, ctx: Arc<Context>) -> Result<Action, kube::Error> {
    let client = &ctx.client;
    let ns = agent.namespace().unwrap_or_else(|| "default".into());
    let name = agent.name_any();

    info!(agent = %name, namespace = %ns, mode = ?agent.spec.mode, "reconciling");

    // Provision StyreneID if identity is configured.
    if agent.spec.identity.as_ref().is_some_and(|id| id.provision) {
        match crate::identity::provision_identity(client, &agent, &ns, &name).await {
            Ok(provisioned) => {
                info!(
                    agent = %name,
                    secret = %provisioned.secret_name,
                    mesh_role = %provisioned.mesh_role,
                    rns_dest = %provisioned.rns_destination_hash,
                    wg_pub = %provisioned.wireguard_pubkey,
                    "identity provisioned"
                );
            }
            Err(crate::identity::IdentityError::NotConfigured) => {}
            Err(e) => {
                warn!(agent = %name, error = %e, "identity provisioning failed");
            }
        }
    }

    // Ensure ConfigMap for vox.toml
    reconcile_configmap(client, &agent, &ns, &name).await?;

    // Ensure workload
    match agent.spec.mode {
        AgentMode::Daemon => {
            reconcile_deployment(client, &agent, &ns, &name).await?;
            reconcile_service(client, &agent, &ns, &name).await?;
        }
        AgentMode::Cronjob => {
            reconcile_cronjob(client, &agent, &ns, &name).await?;
        }
        AgentMode::Job => {
            reconcile_job(client, &agent, &ns, &name).await?;
        }
    }

    // Ensure prompt ConfigMap for job/cronjob with inline prompt
    if matches!(agent.spec.mode, AgentMode::Job | AgentMode::Cronjob) {
        reconcile_prompt_configmap(client, &agent, &ns, &name).await?;
    }

    info!(agent = %name, "reconciliation complete");
    Ok(Action::requeue(std::time::Duration::from_secs(300)))
}

/// Handle reconciliation errors.
pub fn error_policy(agent: Arc<OmegonAgent>, error: &kube::Error, _ctx: Arc<Context>) -> Action {
    warn!(
        agent = %agent.name_any(),
        error = %error,
        "reconcile error — retrying in 30s"
    );
    Action::requeue(std::time::Duration::from_secs(30))
}

async fn reconcile_configmap(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<ConfigMap> = Api::namespaced(client.clone(), ns);
    let cm_name = format!("{name}-vox");

    let mut vox_toml = String::from("# Generated by auspex-operator\n");

    if let Some(ref discord) = agent.spec.vox.discord {
        vox_toml.push_str("\n[discord]\n");
        vox_toml.push_str(&format!("require_mention = {}\n", discord.require_mention));
        if let Some(ref gid) = discord.guild_id {
            vox_toml.push_str(&format!("guild_id = \"{gid}\"\n"));
        }
    }

    if let Some(ref slack) = agent.spec.vox.slack {
        vox_toml.push_str("\n[slack]\n");
        if let Some(ref ws) = slack.workspace {
            vox_toml.push_str(&format!("workspace = \"{ws}\"\n"));
        }
    }

    let cm = json!({
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": cm_name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "data": {
            "vox.toml": vox_toml,
        }
    });

    api.patch(
        &cm_name,
        &PatchParams::apply("auspex-operator"),
        &Patch::Apply(cm),
    )
    .await?;
    Ok(())
}

async fn reconcile_deployment(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<Deployment> = Api::namespaced(client.clone(), ns);

    let tpl = pod_spec(agent, name);
    let mut template_metadata = json!({ "labels": { "styrene.sh/agent": name } });
    if let Some(ref annotations) = tpl.annotations {
        template_metadata
            .as_object_mut()
            .unwrap()
            .insert("annotations".into(), annotations.clone());
    }

    let deploy = json!({
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "spec": {
            "replicas": 1,
            "selector": { "matchLabels": { "styrene.sh/agent": name } },
            "template": {
                "metadata": template_metadata,
                "spec": tpl.spec,
            }
        }
    });

    api.patch(
        name,
        &PatchParams::apply("auspex-operator"),
        &Patch::Apply(deploy),
    )
    .await?;
    Ok(())
}

async fn reconcile_cronjob(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<CronJob> = Api::namespaced(client.clone(), ns);
    let schedule = agent.spec.schedule.as_deref().unwrap_or("0 * * * *");

    let tpl = pod_spec(agent, name);
    let mut spec = tpl.spec;
    spec.as_object_mut()
        .unwrap()
        .insert("restartPolicy".into(), json!("Never"));

    let mut template_metadata = json!({ "labels": { "styrene.sh/agent": name } });
    if let Some(ref annotations) = tpl.annotations {
        template_metadata
            .as_object_mut()
            .unwrap()
            .insert("annotations".into(), annotations.clone());
    }

    let cj = json!({
        "apiVersion": "batch/v1",
        "kind": "CronJob",
        "metadata": {
            "name": name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "spec": {
            "schedule": schedule,
            "concurrencyPolicy": "Forbid",
            "successfulJobsHistoryLimit": 3,
            "failedJobsHistoryLimit": 3,
            "jobTemplate": {
                "spec": {
                    "backoffLimit": 1,
                    "template": {
                        "metadata": template_metadata,
                        "spec": spec,
                    }
                }
            }
        }
    });

    api.patch(
        name,
        &PatchParams::apply("auspex-operator"),
        &Patch::Apply(cj),
    )
    .await?;
    Ok(())
}

async fn reconcile_job(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<Job> = Api::namespaced(client.clone(), ns);

    let tpl = pod_spec(agent, name);
    let mut spec = tpl.spec;
    spec.as_object_mut()
        .unwrap()
        .insert("restartPolicy".into(), json!("Never"));

    let mut template_metadata = json!({ "labels": { "styrene.sh/agent": name } });
    if let Some(ref annotations) = tpl.annotations {
        template_metadata
            .as_object_mut()
            .unwrap()
            .insert("annotations".into(), annotations.clone());
    }

    let active_deadline = agent
        .spec
        .bounds
        .as_ref()
        .and_then(|b| b.active_deadline_seconds);

    let mut job_spec = json!({
        "backoffLimit": 0,
        "template": {
            "metadata": template_metadata,
            "spec": spec,
        }
    });

    if let Some(deadline) = active_deadline {
        job_spec
            .as_object_mut()
            .unwrap()
            .insert("activeDeadlineSeconds".into(), json!(deadline));
    }

    let job = json!({
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
            "name": name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "spec": job_spec,
    });

    api.patch(
        name,
        &PatchParams::apply("auspex-operator"),
        &Patch::Apply(job),
    )
    .await?;
    Ok(())
}

async fn reconcile_prompt_configmap(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let inline = agent.spec.prompt.as_ref().and_then(|p| p.inline.as_deref());

    let Some(prompt_text) = inline else {
        return Ok(());
    };

    let api: Api<ConfigMap> = Api::namespaced(client.clone(), ns);
    let cm_name = format!("{name}-prompt");

    let cm = json!({
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": cm_name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "data": {
            "prompt.txt": prompt_text,
        }
    });

    api.patch(
        &cm_name,
        &PatchParams::apply("auspex-operator"),
        &Patch::Apply(cm),
    )
    .await?;
    Ok(())
}

async fn reconcile_service(
    client: &Client,
    agent: &OmegonAgent,
    ns: &str,
    name: &str,
) -> Result<(), kube::Error> {
    let api: Api<Service> = Api::namespaced(client.clone(), ns);

    let svc = json!({
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": name,
            "namespace": ns,
            "ownerReferences": [owner_ref(agent)],
        },
        "spec": {
            "selector": { "styrene.sh/agent": name },
            "ports": [{
                "port": 7842,
                "targetPort": 7842,
                "protocol": "TCP",
                "name": "control",
            }],
        }
    });

    api.patch(
        name,
        &PatchParams::apply("auspex-operator"),
        &Patch::Apply(svc),
    )
    .await?;
    Ok(())
}

fn pod_spec(agent: &OmegonAgent, name: &str) -> PodTemplate {
    let is_bounded = matches!(agent.spec.mode, AgentMode::Job | AgentMode::Cronjob);
    let has_aether = agent.spec.vox.connectors.iter().any(|c| c == "aether");
    let control_tls = resolved_control_tls(agent, name);

    let mut env = vec![
        json!({"name": "VOX_CONFIG_PATH", "value": "/config/vox"}),
        json!({"name": "AETHER_WORKER_ROLE", "value": &agent.spec.role}),
    ];
    if let Some(ref discord) = agent.spec.vox.discord {
        if let Some(ref gid) = discord.guild_id {
            env.push(json!({"name": "VOX_DISCORD_GUILD_ID", "value": gid}));
        }
    }

    // When aether is enabled, set the styrened socket path and extensions dir.
    if has_aether {
        env.push(json!({"name": "STYRENED_SOCKET", "value": "/shared/styrened.sock"}));
        env.push(json!({"name": "OMEGON_EXTENSIONS_PATH", "value": "/extensions"}));
    }

    // Inject profile reference as annotation for SBOM tracking.
    if let Some(ref profile) = agent.spec.profile {
        env.push(json!({"name": "OMEGON_PROFILE", "value": profile}));
    }

    // StyreneID env vars (volumes mounted below after declaration).
    if agent.spec.identity.as_ref().is_some_and(|id| id.provision) {
        env.push(json!({
            "name": "STYRENE_IDENTITY_PATH",
            "value": "/run/styrene/identity/root-secret"
        }));
        let role = agent
            .spec
            .identity
            .as_ref()
            .map(|id| id.mesh_role.as_str())
            .unwrap_or("operator");
        env.push(json!({"name": "STYRENE_MESH_ROLE", "value": role}));
    }

    // Mount vox config at a well-known path that doesn't assume root home.
    // Omegon reads VOX_CONFIG_PATH if set, falling back to ~/.config/vox.
    let mut volume_mounts = vec![json!({
        "name": "vox-config",
        "mountPath": "/config/vox",
    })];
    let mut volumes = vec![json!({
        "name": "vox-config",
        "configMap": { "name": format!("{name}-vox") },
    })];

    if has_aether {
        // Shared volume for Unix socket between agent and styrened sidecar.
        volumes.push(json!({
            "name": "shared",
            "emptyDir": { "medium": "Memory", "sizeLimit": "10Mi" },
        }));
        volume_mounts.push(json!({
            "name": "shared",
            "mountPath": "/shared",
        }));

        // Extensions volume (populated by init container).
        volumes.push(json!({
            "name": "extensions",
            "emptyDir": {},
        }));
        volume_mounts.push(json!({
            "name": "extensions",
            "mountPath": "/extensions",
            "readOnly": true,
        }));

        // styrened sidecar config: use per-agent ConfigMap name so each
        // agent can have its own mesh config. Falls back to a shared default.
        let styrened_cm = format!("{name}-styrened");
        volumes.push(json!({
            "name": "styrened-config",
            "configMap": {
                "name": styrened_cm,
                "optional": true,
            },
        }));
    }

    if let Some(ref auth_secret) = agent.spec.secrets.auth_json_secret {
        volume_mounts.push(json!({
            "name": "auth-json",
            "mountPath": "/config/omegon",
            "readOnly": true,
        }));
        volumes.push(json!({
            "name": "auth-json",
            "secret": {
                "secretName": auth_secret,
                "items": [{"key": "auth.json", "path": "auth.json"}],
            },
        }));
    }

    // StyreneID secret volume for mesh identity.
    if agent.spec.identity.as_ref().is_some_and(|id| id.provision) {
        let secret_name = format!("{name}-styrene-id");
        volumes.push(json!({
            "name": "styrene-id",
            "secret": {
                "secretName": secret_name,
                "items": [{"key": "root-secret", "path": "root-secret"}],
            },
        }));
        volume_mounts.push(json!({
            "name": "styrene-id",
            "mountPath": "/run/styrene/identity",
            "readOnly": true,
        }));
    }

    if let Some(tls) = control_tls.as_ref() {
        let mut items = vec![
            json!({"key": tls.cert_key, "path": "tls.crt"}),
            json!({"key": tls.key_key, "path": "tls.key"}),
        ];
        if let Some(client_ca_key) = tls.client_ca_key.as_ref() {
            items.push(json!({"key": client_ca_key, "path": "ca.crt"}));
        }
        volumes.push(json!({
            "name": "control-tls",
            "secret": {
                "secretName": tls.secret_name,
                "items": items,
            },
        }));
        volume_mounts.push(json!({
            "name": "control-tls",
            "mountPath": CONTROL_TLS_MOUNT_PATH,
            "readOnly": true,
        }));
    }

    let mut env_from = vec![];
    if let Some(ref secret_name) = agent.spec.secrets.secret_name {
        env_from.push(json!({"secretRef": {"name": secret_name}}));
    }

    // Prompt/output mounts for bounded modes.
    if is_bounded {
        let prompt_mount_path = agent
            .spec
            .prompt
            .as_ref()
            .map(|p| p.mount_path.as_str())
            .unwrap_or("/input/prompt.txt");
        let prompt_dir = prompt_mount_path
            .rsplit_once('/')
            .map(|(d, _)| d)
            .unwrap_or("/input");

        // Prompt volume: from Secret (sensitive), ConfigMap (inline), or user-provided.
        // Priority: secret > inline (stored as ConfigMap) > config_map reference.
        let prompt_spec = agent.spec.prompt.as_ref();
        if let Some(secret_name) = prompt_spec.and_then(|p| p.secret.as_ref()) {
            volumes.push(json!({
                "name": "prompt",
                "secret": {
                    "secretName": secret_name,
                    "items": [{"key": "prompt.txt", "path": "prompt.txt"}],
                },
            }));
            volume_mounts.push(json!({
                "name": "prompt",
                "mountPath": prompt_dir,
                "readOnly": true,
            }));
        } else if prompt_spec.and_then(|p| p.inline.as_ref()).is_some() {
            volumes.push(json!({
                "name": "prompt",
                "configMap": { "name": format!("{name}-prompt") },
            }));
            volume_mounts.push(json!({
                "name": "prompt",
                "mountPath": prompt_dir,
                "readOnly": true,
            }));
        } else if let Some(cm) = prompt_spec.and_then(|p| p.config_map.as_ref()) {
            volumes.push(json!({
                "name": "prompt",
                "configMap": { "name": cm },
            }));
            volume_mounts.push(json!({
                "name": "prompt",
                "mountPath": prompt_dir,
                "readOnly": true,
            }));
        }

        // Output volume for structured results.
        volumes.push(json!({
            "name": "output",
            "emptyDir": {},
        }));
        volume_mounts.push(json!({
            "name": "output",
            "mountPath": "/output",
        }));
    }

    // Build container args: `run` for bounded modes, `serve` for daemon.
    let mut args: Vec<String> = if is_bounded {
        vec!["run".into()]
    } else {
        vec![
            "serve".into(),
            "--control-port".into(),
            "7842".into(),
            "--strict-port".into(),
        ]
    };

    if !is_bounded && let Some(tls) = control_tls.as_ref() {
        args.extend([
            "--control-tls-cert".into(),
            format!("{CONTROL_TLS_MOUNT_PATH}/tls.crt"),
            "--control-tls-key".into(),
            format!("{CONTROL_TLS_MOUNT_PATH}/tls.key"),
        ]);
        if tls.client_ca_key.is_some() {
            args.extend([
                "--control-tls-client-ca".into(),
                format!("{CONTROL_TLS_MOUNT_PATH}/ca.crt"),
            ]);
        }
    }

    args.extend(["--agent".into(), agent.spec.agent.clone()]);
    args.extend(["--model".into(), agent.spec.model.clone()]);
    args.extend(["--posture".into(), agent.spec.posture.clone()]);

    // Append resource bounds for bounded modes.
    if let Some(ref bounds) = agent.spec.bounds {
        if let Some(turns) = bounds.max_turns {
            args.extend(["--max-turns".into(), turns.to_string()]);
        }
        if let Some(timeout) = bounds.timeout {
            args.extend(["--timeout".into(), timeout.to_string()]);
        }
        if let Some(budget) = bounds.token_budget {
            args.extend(["--token-budget".into(), budget.to_string()]);
        }
        if let Some(ref ctx_class) = bounds.context_class {
            args.extend(["--context-class".into(), ctx_class.clone()]);
        }
    }

    // Prompt and output paths for bounded modes.
    if is_bounded {
        if let Some(ref prompt) = agent.spec.prompt {
            args.extend(["--prompt-file".into(), prompt.mount_path.clone()]);
            args.extend(["--output".into(), prompt.output_path.clone()]);
        }
    }

    // Build container list: agent + optional styrened sidecar.
    let mut agent_container = json!({
        "name": "agent",
        "image": &agent.spec.image,
        "args": args,
        "env": env,
        "envFrom": env_from,
        "volumeMounts": volume_mounts,
    });

    // Daemon mode gets health probes and exposed ports.
    if !is_bounded {
        let container = agent_container.as_object_mut().unwrap();
        container.insert("ports".into(), json!([{"containerPort": 7842}]));
        let probe_scheme = if control_tls.is_some() {
            "HTTPS"
        } else {
            "HTTP"
        };
        container.insert(
            "livenessProbe".into(),
            json!({
                "httpGet": { "path": "/api/healthz", "port": 7842, "scheme": probe_scheme },
                "initialDelaySeconds": 15,
                "periodSeconds": 30,
            }),
        );
        container.insert(
            "readinessProbe".into(),
            json!({
                "httpGet": { "path": "/api/readyz", "port": 7842, "scheme": probe_scheme },
                "initialDelaySeconds": 10,
                "periodSeconds": 10,
            }),
        );
    }

    // Resource limits from spec.
    if let Some(ref res) = agent.spec.resources {
        let mut requests = serde_json::Map::new();
        let mut limits = serde_json::Map::new();
        if let Some(ref cpu) = res.cpu {
            requests.insert("cpu".into(), json!(cpu));
            limits.insert("cpu".into(), json!(cpu));
        }
        if let Some(ref mem) = res.memory {
            requests.insert("memory".into(), json!(mem));
            limits.insert("memory".into(), json!(mem));
        }
        if !requests.is_empty() {
            agent_container.as_object_mut().unwrap().insert(
                "resources".into(),
                json!({ "requests": requests, "limits": limits }),
            );
        }
    }

    let mut containers = vec![agent_container];

    // styrened sidecar: provides mesh transport via Unix socket.
    if has_aether {
        let has_identity = agent.spec.identity.as_ref().is_some_and(|id| id.provision);

        let mut styrened_env =
            vec![json!({"name": "STYRENED_SOCKET", "value": "/shared/styrened.sock"})];
        let mut styrened_mounts = vec![
            json!({"name": "shared", "mountPath": "/shared"}),
            json!({"name": "styrened-config", "mountPath": "/etc/styrene", "readOnly": true}),
        ];

        // Share the StyreneID with styrened so it can announce on RNS
        // with the same identity the operator pre-authorized.
        if has_identity {
            styrened_mounts.push(json!({
                "name": "styrene-id",
                "mountPath": "/run/styrene/identity",
                "readOnly": true,
            }));
            styrened_env.push(json!({
                "name": "STYRENE_IDENTITY_PATH",
                "value": "/run/styrene/identity/root-secret"
            }));
        }

        containers.push(json!({
            "name": "styrened",
            "image": styrened_image(),
            "env": styrened_env,
            "ports": [
                { "containerPort": 9101, "name": "metrics", "protocol": "TCP" },
            ],
            "volumeMounts": styrened_mounts,
            "resources": {
                "requests": { "cpu": "50m", "memory": "64Mi" },
                "limits": { "cpu": "200m", "memory": "128Mi" },
            },
        }));
    }

    // Init container: copy aether extension binary into shared volume.
    let init_containers = if has_aether {
        json!([{
            "name": "install-aether",
            "image": aether_image(),
            "command": ["/bin/sh", "-c",
                "mkdir -p /extensions/aether && \
                 cp /usr/local/bin/aether /extensions/aether/aether && \
                 cp /usr/local/lib/omegon/extensions/aether/manifest.toml /extensions/aether/manifest.toml"
            ],
            "volumeMounts": [
                { "name": "extensions", "mountPath": "/extensions" },
            ],
        }])
    } else {
        json!([])
    };

    // Annotations for SBOM, profile, and Vault injection.
    let mut annotations = serde_json::Map::new();
    if let Some(ref profile) = agent.spec.profile {
        annotations.insert("styrene.sh/profile".into(), json!(profile));
    }
    if let Some(ref sbom) = agent.spec.sbom {
        if sbom.enabled {
            annotations.insert("styrene.sh/sbom-format".into(), json!(&sbom.format));
            if let Some(ref artifact) = sbom.artifact_ref {
                annotations.insert("styrene.sh/sbom-ref".into(), json!(artifact));
            }
        }
    }

    // Vault Agent injector annotations: when vault secrets are configured,
    // annotate the pod so the Vault Agent sidecar injects secrets directly.
    // This means secrets never pass through the operator's memory or k8s Secrets.
    if let Some(ref vault) = agent.spec.secrets.vault {
        if vault.agent_inject {
            annotations.insert("vault.hashicorp.com/agent-inject".into(), json!("true"));
            if let Some(ref role) = vault.role {
                annotations.insert("vault.hashicorp.com/role".into(), json!(role));
            }
            if let Some(ref addr) = vault.address {
                annotations.insert(
                    "vault.hashicorp.com/agent-inject-status".into(),
                    json!("update"),
                );
                annotations.insert("vault.hashicorp.com/agent-address".into(), json!(addr));
            }
            for mapping in &vault.secrets {
                // The annotation suffix becomes the filename under /vault/secrets/.
                // Sanitize the destination to a safe annotation key suffix.
                let suffix = mapping
                    .destination
                    .trim_start_matches('/')
                    .replace('/', "-");

                annotations.insert(
                    format!("vault.hashicorp.com/agent-inject-secret-{suffix}"),
                    json!(&mapping.path),
                );
                if let Some(ref template) = mapping.template {
                    annotations.insert(
                        format!("vault.hashicorp.com/agent-inject-template-{suffix}"),
                        json!(template),
                    );
                }
            }
        }
    }

    let pod_spec = json!({
        "initContainers": init_containers,
        "containers": containers,
        "volumes": volumes,
        "terminationGracePeriodSeconds": if is_bounded { 30 } else { 60 },
    });

    PodTemplate {
        spec: pod_spec,
        annotations: if annotations.is_empty() {
            None
        } else {
            Some(json!(annotations))
        },
    }
}

/// Pod template with spec and optional annotations for the template metadata.
pub struct PodTemplate {
    pub spec: serde_json::Value,
    pub annotations: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedControlTls {
    pub secret_name: String,
    pub cert_key: String,
    pub key_key: String,
    pub client_ca_key: Option<String>,
}

pub fn control_plane_tls_enabled(agent: &OmegonAgent) -> bool {
    agent.spec.control_plane.tls.enabled || agent.spec.identity.as_ref().is_some_and(|id| id.mtls)
}

pub fn resolved_control_tls(agent: &OmegonAgent, name: &str) -> Option<ResolvedControlTls> {
    if !control_plane_tls_enabled(agent) {
        return None;
    }

    let tls = &agent.spec.control_plane.tls;
    Some(ResolvedControlTls {
        secret_name: tls
            .secret_name
            .clone()
            .unwrap_or_else(|| format!("{name}-control-tls")),
        cert_key: tls.cert_key.clone(),
        key_key: tls.key_key.clone(),
        client_ca_key: tls.client_ca_key.clone(),
    })
}

pub fn owner_ref(agent: &OmegonAgent) -> serde_json::Value {
    json!({
        "apiVersion": "styrene.sh/v1alpha1",
        "kind": "OmegonAgent",
        "name": agent.name_any(),
        "uid": agent.metadata.uid.as_deref().unwrap_or(""),
        "controller": true,
        "blockOwnerDeletion": true,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn daemon_agent(value: serde_json::Value) -> OmegonAgent {
        serde_json::from_value(value).expect("valid OmegonAgent")
    }

    #[test]
    fn pod_spec_mounts_tls_secret_and_passes_control_tls_args() {
        let agent = daemon_agent(serde_json::json!({
            "apiVersion": "styrene.sh/v1alpha1",
            "kind": "OmegonAgent",
            "metadata": {
                "name": "secure-primary",
                "namespace": "omegon-agents"
            },
            "spec": {
                "agent": "styrene.secure-primary",
                "model": "anthropic:claude-sonnet-4-6",
                "role": "primary-driver",
                "mode": "daemon",
                "controlPlane": {
                    "tls": {
                        "enabled": true,
                        "secretName": "secure-primary-control-tls"
                    }
                }
            }
        }));

        let template = pod_spec(&agent, "secure-primary");
        let agent_container = &template.spec["containers"][0];
        let args = agent_container["args"].as_array().expect("args array");
        let args: Vec<_> = args.iter().filter_map(|value| value.as_str()).collect();

        assert!(args.contains(&"--control-tls-cert"));
        assert!(args.contains(&"/run/omegon/control-tls/tls.crt"));
        assert!(args.contains(&"--control-tls-key"));
        assert!(args.contains(&"/run/omegon/control-tls/tls.key"));
        assert!(args.contains(&"--control-tls-client-ca"));
        assert!(args.contains(&"/run/omegon/control-tls/ca.crt"));
        assert_eq!(
            agent_container["readinessProbe"]["httpGet"]["scheme"],
            "HTTPS"
        );
        assert_eq!(
            template.spec["volumes"]
                .as_array()
                .expect("volumes")
                .iter()
                .find(|volume| volume["name"] == "control-tls")
                .expect("control TLS volume")["secret"]["secretName"],
            "secure-primary-control-tls"
        );
    }

    #[test]
    fn identity_mtls_uses_default_control_tls_secret() {
        let agent = daemon_agent(serde_json::json!({
            "apiVersion": "styrene.sh/v1alpha1",
            "kind": "OmegonAgent",
            "metadata": {
                "name": "primary-driver",
                "namespace": "omegon-agents"
            },
            "spec": {
                "agent": "styrene.primary",
                "model": "anthropic:claude-sonnet-4-6",
                "role": "primary-driver",
                "mode": "daemon",
                "identity": {
                    "provision": true,
                    "mtls": true
                }
            }
        }));

        let tls = resolved_control_tls(&agent, "primary-driver").expect("resolved TLS");

        assert_eq!(tls.secret_name, "primary-driver-control-tls");
        assert_eq!(tls.client_ca_key.as_deref(), Some("ca.crt"));
    }
}
