apiVersion: v1
kind: Service
metadata:
  name: auspex-operator
  labels:
    app.kubernetes.io/name: auspex-operator
    app.kubernetes.io/part-of: auspex
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auspex-operator
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: mqtt
      port: 1883
      targetPort: mqtt
